export const CHANGE_SORT_BY_REGISTRATION_NUMBERS =
  'AIS_REGISTRIES/REGISTERED_REDUCER/CHANGE_SORT_BY_REGISTRATION_NUMBERS';
export const CHANGE_SORT_BY_REGISTRATION_NAMES_SOFTWARE =
  'AIS_REGISTRIES/REGISTERED_REDUCER/CHANGE_SORT_BY_REGISTRATION_NAMES_SOFTWARE';
export const SET_REGISTRATION_SEARCH =
  'AIS_REGISTRIES/REGISTERED_REDUCER/SET_REGISTRATION_SEARCH';
